### ISSUE TITLE
Code for Fine-Tuning

### ISSUE THREAD

**Issue by qutrino** [Veason-silverbullet/ViTLP#2]
Thank you for sharing such excellent paper and code. 
Do you have any plans to release the fine-tuning code for the CORD or FUNSD datasets to reproduce the results in the paper?

**Comment by Veason-silverbullet** [comment]
Hi, @qutrino . I am very sorry that codes/models for CORD or FUNSD are not available because I ended my internship on April 30. As far as I know, due to the company's policy, only the base model is allowed to be open-sourced, other downstream codes/models are not available.

**Comment by qutrino** [comment]
@Veason-silverbullet 
Thank you for your prompt response!
