### ISSUE TITLE
The values provided by the bbox are incorrect, 

### ISSUE THREAD

**Issue by prosmans** [Veason-silverbullet/ViTLP#6]
The values provided by the bbox are incorrect,  In this example, the top-left corner of "example" is 54-64, and the bottom-right corner is 116-84. However, as shown in the image, my measurements do not encompass the word "Example."

![image](https://github.com/user-attachments/assets/d424c1cd-5f14-4d15-b763-60ce049f6204)

**Comment by Veason-silverbullet** [comment]
Note that the output bounding boxes are normalized into [0, 1000], pls double-check.

**Comment by Veason-silverbullet** [comment]
@jingk-1992 
Note that the output bounding boxes are normalized into [0, 1000], but not absolute values. Please double-check.
